name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and cache client dependencies
        uses: bahmutov/npm-install@v1

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Push to Server
        run: |
          git remote add server git@codies.se:repos/zone-fighter.git
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git add server dist -f
          git commit -m "Build files"
          git push -u server HEAD:main -f
